"""
InvestigatorState — the central TypedDict driving the LangGraph state machine.

Fields annotated with `operator.add` are *reducer* fields: each node's return
value is **appended** to the existing list rather than overwriting it.
"""

import operator
from typing import Annotated, List, Optional, TypedDict


class InvestigatorState(TypedDict):
    """Shared state threaded through every node in the investigation graph."""

    # --- Identity ---
    investigation_id: str  # Unique slug per run; namespaces all data stores

    # --- Input ---
    investigation_target: str  # Vague description or name from the user
    target_name: Optional[str]  # Resolved official name (set by Planner)

    # --- Planning ---
    queries: List[str]  # Search queries generated by the Planner

    # --- Gathering (reducer fields — values are appended, not overwritten) ---
    raw_context: Annotated[list[str], operator.add]
    extracted_entities: Annotated[list[dict], operator.add]
    extracted_relationships: Annotated[list[dict], operator.add]

    # --- Workflow Control ---
    current_phase: str  # "ingestion" | "chat"
    iteration_count: int  # Current feedback-loop iteration
    max_iterations: int  # Cap to prevent infinite re-planning
    max_search_results: int  # Max results from DuckDuckGo/NewsAPI
    scrape_content_chars_max: int  # Max chars to extract per chunk
    planner_query_count: int  # Number of initial queries to generate

    # --- Expansion Control ---
    lateral_expansion_depth: int  # How many levels deep to cross-reference entities
    current_expansion_depth: int  # Tracks the current hop count
    max_entities_to_expand: (
        int  # Limit how many entities the planner can expand per hop
    )

    # --- Chat Q&A ---
    chat_question: str
    synthesized_answer: str

    # --- Proactive Intelligence ---
    briefing: str  # Auto-generated after ingestion
